<!DOCTYPE html>
<html>
<head>
    <title>Student Health Report - {{ $student->full_name }}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #333; padding-bottom: 20px; }
        .header-container { display: flex; align-items: center; justify-content: center; gap: 20px; margin-bottom: 15px; }
        .logo { max-width: 80px; max-height: 80px; }
        .header-text { flex: 1; }
        .section { margin-bottom: 25px; }
        .section-title { background-color: #f8f9fa; padding: 10px; font-weight: bold; border-left: 4px solid #007bff; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f8f9fa; }
        .stats-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 15px; margin-bottom: 20px; }
        .stat-card { border: 1px solid #ddd; padding: 15px; text-align: center; }
        .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #666; }
        @media print {
            .no-print { display: none; }
            body { margin: 0; }
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="header-container">
            <img src="https://scontent.fmnl13-4.fna.fbcdn.net/v/t39.30808-6/510989554_1291512086313864_1697600367017083003_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=6ee11a&_nc_ohc=ufmPlgigja8Q7kNvwF_30_x&_nc_oc=AdlrVYVNZAzO_DGs6ZEPjA4md988p2i11ak9QgVeBj4BwvzoytYbd1KnPkJEmid5YjyY_JwK9qwtz50ZYfdvBf8K&_nc_zt=23&_nc_ht=scontent.fmnl13-4.fna&_nc_gid=xGwgW7kWmHtNvco3LOav9g&oh=00_AfcNlqpnEt7uahZF64yHtUjKLb9QOFvbtJEkStvCYQ5-9A&oe=68F5CA67" 
                 alt="School Logo" class="logo">
            <div class="header-text">
                <h1>Student Health Report</h1>
                <h2>{{ $student->full_name }} ({{ $student->student_id }})</h2>
                <p>Generated on: {{ now()->format('F j, Y g:i A') }}</p>
            </div>
        </div>
    </div>

    <div class="section">
        <div class="section-title">Student Information</div>
        <p><strong>Name:</strong> {{ $student->full_name }}</p>
        <p><strong>Student ID:</strong> {{ $student->student_id }}</p>
        <p><strong>Course:</strong> {{ $student->course ?? 'N/A' }}</p>
        <p><strong>Year Level:</strong> {{ $student->year_level ?? 'N/A' }}</p>
        <p><strong>Email:</strong> {{ $student->email }}</p>
    </div>

    <div class="section">
        <div class="section-title">Health Statistics Overview</div>
        <div class="stats-grid">
            <div class="stat-card">
                <h3>{{ $healthStats['total_consultations'] }}</h3>
                <p>Consultations</p>
            </div>
            <div class="stat-card">
                <h3>{{ $healthStats['total_symptoms_logged'] }}</h3>
                <p>Symptoms Logged</p>
            </div>
            <div class="stat-card">
                <h3>{{ $healthStats['total_appointments'] }}</h3>
                <p>Appointments</p>
            </div>
            <div class="stat-card">
                <h3>{{ $healthStats['medical_record_completion'] }}%</h3>
                <p>Record Complete</p>
            </div>
        </div>
    </div>

    <div class="footer">
        <p>Confidential Health Report - For authorized personnel only</p>
        <p>Generated by: {{ auth()->user()->full_name }}</p>
    </div>

    <div class="no-print text-center mt-4">
        <button onclick="window.print()" class="btn btn-primary">Print Report</button>
        <button onclick="window.close()" class="btn btn-secondary">Close</button>
    </div>
</body>
</html>